config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  

  resources :notes
  resources :foods
  namespace :entrenador do
    get 'comments/index'
  end

  resources :comments
  namespace :admin do
    get 'welcome/index'
  end

  root 'welcome#index'
  
  get 'registro', to: 'clients#new'
  get 'login-client', to: 'clients#front'
  post 'login-c', to: 'clients#login'
  get 'login-coach', to:'coaches#front'
  post 'login-coach-back', to: 'coaches#login'
  
  resources :assessments
  resources :posts
  resources :blogs
  resources :clients
  resources :coaches
  resources :disciplines
  resources :exercises
  resources :categories
  
  

  # Change path to '/' if you want direct access to users views
  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks',
    omniauth: 'users/omniauth'
  }, paths: {confirmation: 'verification'}
  namespace :client do
    root 'welcome#index'
    resources :valorar
    resources :routines
    resources :calculate
    resources :comments
    resources :blogs do
      resources :posts
    end
    resources :notes
    get 'profile/index'
    put 'profile/update'
    post 'routines/created'
  end
  namespace :entrenador do
    root 'welcome#index'
    resources :comments
    get 'commentarios', to: "comments#backend"
    resources :blogs do
      resources :posts
    end
    resources :posts
    resources :clients
    get 'profile', to: "profile#index"
    put 'profile/update'
    
  end

  namespace :admin do
    root 'welcome#index'
    resources :clients
    resources :coaches
    resources :disciplines
    resources :exercises
    resources :categories
  end

end

app/models/client.rb
class Client < ApplicationRecord
  
  include BCrypt
  belongs_to :coach
    def password
      @password ||= Password.new(password_hash)
    end
  
    def password=(new_password)
      @password = Password.create(new_password)
      self.password_hash = @password
    end
end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < Admin::ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    
  end

  # GET /clients/new
  def new
    @client = Client.new

    puts Coach.all.count
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    @client.password = params[:client][:password]
    
      if @client.save
         redirect_to root_path
      else
        render :new 
      end
    
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def front
  end
  
  def login
    @client = Client.where(user: params[:user]).first
    puts @client.password
    puts params[:password]
    if @client.password == params[:password]
      puts "ok"
      render json: @client
    else
      render json: {},status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :lastname, :phone, :address, :coach_id, :user, :password)
    end
end

app/controllers/client/application_controller.rb
class Client::ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  layout 'client'
  end
  

app/controllers/client/blogs_controller.rb
class Client::BlogsController < Client::ApplicationController
    layout 'client'
    def index
        @client = Client.find(params[:uid])
        @coach = Coach.find(@client.coach_id)
        @blog = Blog.find(@coach.id)

    end
    
    def show
        @blog = Blog.find(params[:id])
        @posts = @blog.posts.order("created_at DESC")
    end
  end
  

app/controllers/client/calculate_controller.rb
class Client::CalculateController < Client::ApplicationController
	layout 'client'
	def index
		@food = Food.all
	end
end

app/controllers/client/comments_controller.rb
class Client::CommentsController < Client::ApplicationController
  protect_from_forgery with: :null_session
    def create
      @comment = Comment.new
      @comment.coach_id = params[:coach_id]
      @comment.value = params[:comment][:value]
      uid = "#{params[:uid]}"
      clie = Client.find(uid)
      @ass = Assessment.where(client_id: clie.id)
      if @ass.count == 0
        Assessment.create(coach_id: params[:coach_id], points: params[:puntos], client_id: clie.id)
      end
        if @comment.save
          render json: @comment
        else
          render json: @comment.errors, status: :unprocessable_entity 
        end
      #
      
      end

      private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:coach_id, :value)
    end
end

app/controllers/client/notes_controller.rb
class Client::NotesController < Client::ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @client = Client.find(params[:uid])
    @note = Note.new
    @note.client_id = @client.id
    @note.coach_id = @client.coach_id
    @note.exercise = params[:ex]
    @note.details = params[:details]
      if @note.save
        render json: @note
      else
        render json: @note.errors, status: :unprocessable_entity
      end
    
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:client_id, :coach_id, :details, :exercise)
    end
end

app/controllers/client/posts_controller.rb
class Client::PostsController < Client::ApplicationController
    layout 'client'
    
    def show
        @post = Post.find(params[:id])
    
    end
  end
  

app/controllers/client/profile_controller.rb
class Client::ProfileController < Client::ApplicationController
  layout 'client'
  def index
    @client = Client.find(params[:uid])
  end

  def update
    if @client.update(client_params)
      render json: @client
    end
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_client
    @client = Client.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def client_params
    params.require(:client).permit(:name, :lastname, :phone, :address, :user, :password)
  end
end

app/controllers/client/routines_controller.rb
class Client::RoutinesController < Client::ApplicationController
    layout 'client'
    protect_from_forgery with: :null_session
    def index
        @client = Client.find(params[:uid])
        @coach = Coach.find(@client.coach_id)
        @blog = Blog.find(@coach.id)

    end
    
    def show
        @blog = Blog.find(params[:id])
        @posts = @blog.posts.order("created_at DESC")
    end
    def new
        @exercises = []
        @all = []
        Exercise.all.each do |ex|
            @exercises.push(ex.name)
            d = {
                desc: ex.description,
                image: ex.imagen.url
            }
            @all.push(d)
        end
        @client = Client.find(params[:uid])
        @superior = Exercise.where(category_id: 1)
        @inferior = Exercise.where(category_id: 2)
        @abdomen = Exercise.where(category_id: 4)
        @cardio = Exercise.where(category_id: 3)


        

    end
    def created
        ex = params[:exercises]
        code = Digest::SHA1.hexdigest(["#{Date.today} #{Time.now}", rand].join)[0..7].to_s.upcase
        client = params[:client_id]
        puts params[:client_id]
        puts code
        
        ex.each do |e|
            exercise = Exercise.where(name: e).first
            puts "--->#{exercise.name}"
            r = Routine.create(code: code, client_id: client,exercise:exercise.name, exercise_id: exercise.id, category: exercise.category.name)
            puts r.errors.messages
        end

        render json: {}
    #     t.integer  "client_id"
    # t.string   "exercise"
    # t.string   "category"
    # t.datetime "created_at",  null: false
    # t.datetime "updated_at",  null: false
    # t.string   "code"
    # t.string   "exercise_id"
    end
  end
  

app/controllers/client/valorar_controller.rb
class Client::ValorarController < Client::ApplicationController
    layout 'client'
    def index
        @client = Client.find(params[:uid])
        @coach = Coach.find(@client.coach_id)
        @blog = Blog.find(@coach.id)

    end
  end
  

app/controllers/client/welcome_controller.rb
class Client::WelcomeController < Client::ApplicationController
  layout 'client'
    def index
      @client = Client.find(params[:uid])
      @coach = Coach.find(@client.coach_id)
      @blog = Blog.find(@coach.id)
    end
    def valorar
    end
  end
  

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)
    @client.password = params[:client][:password]
    
      if @client.save
         redirect_to root_path
      else
        render :new 
      end
    
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def front
  end
  
  def login
    @client = Client.where(user: params[:user]).first
    if @client.password == params[:password]
      puts "ok"
      render json: @client
    else
      render json: {}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :lastname, :phone, :address, :coach_id, :user, :password)
    end
end

app/controllers/entrenador/clients_controller.rb
class Entrenador::ClientsController < Entrenador::BaseController

	def index
		@coach = Coach.find(params[:uid])
		@clients = Client.where(coach_id: params[:uid])
	end
	def show
		@coach = Coach.find(params[:uid])
		@client = Client.find(params[:id])
		@notes = Note.where(client_id: @client.id)
		@routines = Routine.where(client_id: params[:id])
		@data = []
		@routines.group_by(&:exercise).each do |exercise,elements|
			puts exercise
			# d = {
			# 	name:exercise,
			# 	data: elements.count
			# }
			d = [exercise,elements.count]
			@data.push(d)
			
		end

		puts @data

	end

end

app/helpers/client/comment_helper.rb
module Client::CommentHelper
end

app/helpers/client/profile_helper.rb
module Client::ProfileHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/admin/clients/_form.html.erb
<%= form_for(client) do |f| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
      <div class="col-sm">
          <div class="form-group">
              <%= f.label :name, "Nombre" %>
              <%= f.text_field :name, class: 'form-control' %>
            </div>
      </div>
    </div>
  
  <div class="row">
      <div class="col-sm">
          <div class="form-group">
              <%= f.label :lastname, "Apellidos" %>
              <%= f.text_field :lastname, class: 'form-control' %>
          </div>
      </div>
  </div>
  
  <div class="row">
      <div class="col-sm">
          <div class="form-group">
              <%= f.label :phone, "Telefono" %>
              <%= f.text_field :phone, class: 'form-control' %>
            </div>
      </div>
  </div>
  <div class="row">
      <div class="col-sm">
          <div class="form-group">
              <%= f.label :address, "Direccion" %>
              <%= f.text_field :address, class: 'form-control' %>
            </div>
      </div>
  </div>
  <div class="row">
    <div class="col-sm">
      <div class="form-group">
        <%= f.label :coach_id, "Entrenador" %>
        <select name="client[coach_id]" class="custom-select">
            <% Coach.all.each do |c|%>
                <option value="<%=c.id%>"><%=c.name%></option>
            <%end%>
        </select>  
      </div>
    </div>
  </div>
  <div class="row">
      <div class="col-sm">
          <div class="form-group">
              <%= f.label :user, "Usuario" %>
              <%= f.text_field :user, class:'form-control' %>
            </div>
      </div>
  </div>
  <div class="row">
      <div class="col-sm">
          <div class="form-group">
              <%= f.label :password, "Contraseña" %>
              <%= f.password_field :password, class:'form-control' %>
            </div>
      </div>
  </div>
  <div class="row">
      <div class="col-sm">
        <%= f.submit "Registarse", class: 'btn btn-raised btn-primary' %>
      </div>
  </div>

<% end %>

app/views/admin/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/admin/clients/front.html.erb
<div id="loginclient">
        <div class="row" style="margin-top:2em;">
                <div class="col-lg-3"></div>

                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm">
                                    <h3>Iniciar Sesion</h3>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm">
                                    <div class="form-group">
                                        <label for="">Usuario</label>
                                        <input type="text" class="form-control" v-model="user">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                    <div class="col-sm">
                                        <div class="form-group">
                                            <label for="">Contraseña</label>
                                            <input type="password" class="form-control" v-model="password">
                                        </div>
                                    </div>
                            </div>
                            <div class="row justify-content-center">
                                
                                
                                <div class="col-sm-3">
                                    <button class="btn btn-raised btn-primary" @click="ingresar()">Ingresar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
</div>

app/views/admin/clients/index.html.erb
<div class="row">
  <div class="col-sm">
    <h5>Lista de clientes</h5>
  </div>
</div>
<div class="row">
  <div class="col-sm">
      <table class="table">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Apellido</th>
              <th>Telefono</th>
              <!-- <th>Direccion</th> -->
              <th>Entrenador</th>
              <th>Usuario</th>
              <th colspan="3"></th>
            </tr>
          </thead>
        
          <tbody>
            <% @clients.each do |client| %>
              <tr>
                <td class="toUpper"><%= client.name %></td>
                <td class="toUpper"><%= client.lastname %></td>
                <td><%= client.phone %></td>
                <!-- <td><%= client.address %></td> -->
                <td><%= client.coach.name %></td>
                <td><%= client.user %></td>
                <td><%= link_to 'Ver', admin_client_path(client) %></td>
                <td><%= link_to 'Editar', edit_admin_client_path(client) %></td>
                <td><%= link_to 'Eliminar', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        
  </div>
</div>

app/views/admin/clients/new.html.erb
<div class="row" style="margin-top:2em;">
	<div class="col-sm">
		<div class="card">
			<div class="card-body">
					<div class="row">
							<div class="col-sm">
								<h3>Registrate</h3>
							</div>
						</div>
						<div class="row">
							<div class="col-sm">
								<%= render 'form', client: @client %>
							</div>
						</div>
						<div class="row">
							<div class="col-sm">
									<%= link_to 'Regresar', clients_path %>
							</div>
						</div>
			</div>
		</div>
		
	</div>
</div>

app/views/admin/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @client.lastname %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client.address %>
</p>

<p>
  <strong>Coach:</strong>
  <%= @client.coach %>
</p>

<p>
  <strong>User:</strong>
  <%= @client.user %>
</p>

<p>
  <strong>Password:</strong>
  <%= @client.password %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>