config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  

  resources :notes
  resources :foods
  namespace :entrenador do
    get 'comments/index'
  end

  resources :comments
  namespace :admin do
    get 'welcome/index'
  end

  root 'welcome#index'
  
  get 'registro', to: 'clients#new'
  get 'login-client', to: 'clients#front'
  post 'login-c', to: 'clients#login'
  get 'login-coach', to:'coaches#front'
  post 'login-coach-back', to: 'coaches#login'
  
  resources :assessments
  resources :posts
  resources :blogs
  resources :clients
  resources :coaches
  resources :disciplines
  resources :exercises
  resources :categories
  
  

  # Change path to '/' if you want direct access to users views
  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks',
    omniauth: 'users/omniauth'
  }, paths: {confirmation: 'verification'}
  namespace :client do
    root 'welcome#index'
    resources :valorar
    resources :routines
    resources :calculate
    resources :comments
    resources :blogs do
      resources :posts
    end
    resources :notes
    get 'profile/index'
    put 'profile/update'
    post 'routines/created'
  end
  namespace :entrenador do
    root 'welcome#index'
    resources :comments
    get 'commentarios', to: "comments#backend"
    resources :blogs do
      resources :posts
    end
    resources :posts
    resources :clients
    get 'profile', to: "profile#index"
    put 'profile/update'
    
  end

  namespace :admin do
    root 'welcome#index'
    resources :clients
    resources :coaches
    resources :disciplines
    resources :exercises
    resources :categories
  end

end

app/models/assessment.rb
class Assessment < ApplicationRecord
  belongs_to :coach
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :coach
  has_many :posts
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :exercises
end

app/models/client.rb
class Client < ApplicationRecord
  
  include BCrypt
  belongs_to :coach
    def password
      @password ||= Password.new(password_hash)
    end
  
    def password=(new_password)
      @password = Password.create(new_password)
      self.password_hash = @password
    end
end

app/models/coach.rb
class Coach < ApplicationRecord
  include BCrypt
  belongs_to :discipline
  has_one :blog
  has_many :assessments
  has_many :comments

    def password
      @password ||= Password.new(password_hash)
    end
  
    def password=(new_password)
      @password = Password.create(new_password)
      self.password_hash = @password
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :coach
end

app/models/discipline.rb
class Discipline < ApplicationRecord
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :category
  mount_uploader :imagen, FotoUploader
end

app/models/food.rb
class Food < ApplicationRecord
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :client
  belongs_to :coach
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :blog
end

app/models/routine.rb
class Routine < ApplicationRecord
  belongs_to :client
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :recoverable , :lockable
end

app/controllers/admin/exercises_controller.rb
class Admin::ExercisesController < Admin::ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]

  # GET /exercises
  # GET /exercises.json
  def index
    @exercises = Exercise.all
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'Exercise was successfully created.' }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1
  # PATCH/PUT /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to admin_exercises_path, notice: 'Exercise was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url, notice: 'Exercise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exercise_params
      params.require(:exercise).permit(:name, :category_id, :description,:imagen)
    end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]

  # GET /exercises
  # GET /exercises.json
  def index
    @exercises = Exercise.all
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'Exercise was successfully created.' }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1
  # PATCH/PUT /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to @exercise, notice: 'Exercise was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url, notice: 'Exercise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exercise_params
      params.require(:exercise).permit(:name, :category_id)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/exercises/_form.html.erb
<%= form_for([:admin,exercise], html: { multipart: true } ) do |f| %>
  <% if exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
      <% exercise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name,"nombre" %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description, "Descripcion" %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.file_field :imagen %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-raised btn-info' %>
  </div>
<% end %>

app/views/admin/exercises/edit.html.erb
<h1>Editar ejercicio</h1>

<%= render 'form', exercise: @exercise %>


<%= link_to 'Regresar', admin_exercises_path %>

app/views/admin/exercises/index.html.erb
<h1>Ejercicios</h1>

<table class="table striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exercises.group_by(&:category).each do |category,exercises| %>
      <tr>
        <td>
            <h4><%=category.name%></h4>
        </td>
      </tr>
      <%exercises.each do |ex|%>
        <tr>
          
          <td><%= ex.name %></td>
          <td><%= link_to 'Ver', admin_exercise_path(ex) %></td>
          <td><%= link_to 'Editar', edit_admin_exercise_path(ex) %></td>
          <td><%= link_to 'Eliminar', ex, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <%end%>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exercise', new_exercise_path %>

app/views/admin/exercises/new.html.erb
<h1>Nuevo Ejercicio</h1>

<%= render 'form', exercise: @exercise %>

<%= link_to 'Back', exercises_path %>

app/views/admin/exercises/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @exercise.name %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @exercise.category.name %>
</p>
<p>
  <strong>Descripcion: </strong>
  <%=@exercise.description%>
</p>
<p>
  <%= image_tag(@exercise.imagen.url, style: 'width:200px;')%>
</p>
<%= link_to 'Editar', edit_admin_exercise_path(@exercise) %> |
<%= link_to 'Regresar', admin_exercises_path %>